### ISSUE TITLE
大佬，模型似乎有个错误

### ISSUE THREAD

**Issue by OvOYu** [LiuAoyu1998/STAMT#1]
![image](https://github.com/LiuAoyu1998/STAMT/assets/107761563/66328027-2252-4087-b5d7-1fb6ff1aec1f)

**Comment by OvOYu** [comment]
![image](https://github.com/LiuAoyu1998/STAMT/assets/107761563/61841bdf-ecd8-4e7b-aa45-dc45caf01dc1)
发生在这一行

**Comment by OvOYu** [comment]
抱歉，数据集没用对，期待大佬更新下新的npz文件生成的代码！

**Comment by LiuAoyu1998** [comment]
不好意思，才看到，npz文件生成的代码可以参考这个哦https://github.com/SmallNana/STSGCN_Pytorch/blob/master/generate_datasets.py

**Comment by OvOYu** [comment]
大佬，这篇投哪去了 要不先上下arxiv哈哈 follow下大佬的工作！
