### ISSUE TITLE
关于长时间交通预测的输入输出

### ISSUE THREAD

**Issue by wengwenchao123** [LiuAoyu1998/STAMT#2]
大佬，我想问一下，关于长时间交通预测的输入和输出，你是不是就是将短时间交通预测的12对12改成了36对36,48对48,60对60这样子，其他的没有做改变？
另外我想问下，你论文里的结果写的是60对60中，第36,48,60时间步的结果，Average写的是60步的平均结果吗？

谢谢。

**Comment by LiuAoyu1998** [comment]
是的，划分数据集时将12预测12，改成了60预测60。
不过36预测36、48预测48、60预测60的实验都分别做了，后面发现有些冗余，便直接采用60预测60的结果。表4呈现的是60预测60，36、48和60分别是第36、48、60的结果，Average是60步的平均结果。
这就导致在效率实验那块可能有些混淆，在此澄清下Fig.5的结果是在12预测12、36预测36、48预测48、60预测60，4个独立任务上进行统计指标。

**Comment by wengwenchao123** [comment]
好的，谢谢
